[tool.poetry]
name = "tool-for-classify-dependency-removal"
version = "0.1.0"
description = "This tool is a tool for classifying dependency removal in JavaScript projects. The results of the classification are dependency removal with and without direct impact code changes."
authors = ["ppjaisri <ppjaisri@gmail.com>"]
license = "MIT"
readme = "README.md"
packages = [{include = "src"}]

[tool.poetry.dependencies]
python = "^3.12"
poetry = "^2.0.0"
stdlib-list = "^0.11.0"
prompt-toolkit = "^3.0.51"


[tool.poetry.group.dev.dependencies]
ipykernel = "^6.29.5"
jupyter = "^1.1.1"
matplotlib = "^3.10.0"
numpy = "^2.2.3"
graphviz = "^0.20.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
